### ISSUE TITLE
Add Test Coverage Reporting

### ISSUE THREAD

**Issue by timmybird** [PitchConnect/fogis-reporter#93]
# Add Test Coverage Reporting

## Description
We need to add test coverage reporting to the project to ensure code quality and identify areas that need more testing.

## Tasks
- [ ] Create a `.coveragerc` file with appropriate settings
- [ ] Update GitHub Actions workflow to run coverage checks
- [ ] Add Codecov badge to README
- [ ] Add documentation on how to run coverage locally

## Implementation Details
See the detailed implementation plan in the attached PR description: https://github.com/PitchConnect/fogis-reporter/files/pull_request_description_with_changes.md

## Expected Outcome
- Test coverage reporting is configured and working
- CI/CD pipeline includes coverage checks
- Documentation is updated with coverage information

## Current Status
The current test coverage is around 30%. We should aim for a minimum of 60% coverage and gradually increase it as we add more tests.

**Comment by timmybird** [comment]
# Detailed Implementation Plan

## Changes

### 1. Create a `.coveragerc` file with the following content:

```ini
[run]
source = .
omit =
    # Omit test files
    tests/*
    # Omit virtual environment
    .venv/*
    venv/*
    # Omit setup files
    setup.py
    # Omit scripts directory
    scripts/*

[report]
# Exclude lines with pragma comments
exclude_lines =
    pragma: no cover
    def __repr__
    raise NotImplementedError
    if __name__ == .__main__.:    pass
    raise ImportError
    except ImportError:

# Show missing lines in report
show_missing = True

# Set a reasonable precision
precision = 2

[html]
directory = htmlcov

[xml]
output = coverage.xml

[json]
output = coverage.json
```

### 2. Update the GitHub Actions workflow (`.github/workflows/python-ci.yml`):

Change the "Test with pytest and coverage" step to:

```yaml
- name: Test with pytest and coverage
  continue-on-error: true  # Allow tests to fail for now
  run: |
    # Run tests with coverage but don't fail the build if coverage is below threshold
    pytest --cov=. --cov-report=xml --cov-report=term || echo "Tests or coverage threshold failed but continuing the build"
```

And update the "Upload coverage to Codecov" step to:

```yaml
- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v3
  with:
    file: ./coverage.xml
    fail_ci_if_error: true
    verbose: true
```

### 3. Add Codecov badge to README.md:

Add this line after the title:

```markdown
[![codecov](https://codecov.io/gh/PitchConnect/fogis-reporter/branch/main/graph/badge.svg)](https://codecov.io/gh/PitchConnect/fogis-reporter)
```

### 4. Add documentation on test coverage to README.md:

Add this section after the "Pre-commit Hooks" section:

```markdown
#### Test Coverage with pytest-cov

We use pytest-cov to measure test coverage and ensure code quality:

```bash
# Run tests with coverage report
pytest --cov=. --cov-report=term

# Generate HTML coverage report
pytest --cov=. --cov-report=html
```

The configuration is in the `.coveragerc` file. We aim for a minimum coverage threshold of 60% and are continuously working to improve it.
```

## Testing Results

The current test coverage is around 30%. Here's a summary of the coverage report:

```
---------- coverage: platform linux, python 3.10.12-final-0 ----------
Name                             Stmts   Miss   Cover   Missing
---------------------------------------------------------------
api_utils.py                        11      1  90.91%   35
emoji_config.py                      2      0 100.00%
fogis_data_parser.py                55     55   0.00%   3-92
fogis_reporter.py                  966    631  34.68%   35-67, 88, 125-170, 252, 261-316, 336-375, 388-428, 433-553, 561-600, 635, 650-663, 687, 696, 698-728, 795-806, 842, 876, 886-919, 934-966, 1001, 1011-1018, 1034-1037, 1048-1173, 1180-1229, 1288, 1299-1315, 1328-1334, 1337-1340, 1351-1413, 1425-1543, 1561-1602, 1627-1680, 1711-1716, 1749, 1801-1810, 1852-1853, 1891-1927, 1945-1946, 1967-1971, 1987-2001, 2007-2199
match_context.py                    34     34   0.00%   3-58
match_event_table_formatter.py      92     92   0.00%   6-199
---------------------------------------------------------------
TOTAL                             1160    813  29.91%
```

We need to focus on improving the test coverage for `fogis_data_parser.py`, `match_context.py`, and `match_event_table_formatter.py` which currently have 0% coverage.
