### ISSUE TITLE
Add Test Coverage Workflow (PR for Review)

### ISSUE THREAD

**Issue by timmybird** [PitchConnect/fogis-reporter#95]
# Test Coverage Workflow PR

## For the Next Agent

This PR is intended to be reviewed and fixed before merging. Please follow these steps:

1. Create a new branch from `main` called `feature/add-test-coverage-workflow`
2. Create the file `.github/workflows/python-ci-coverage.yml` with the content below
3. Review the workflow file for any issues or improvements
4. Make necessary changes to ensure it works correctly
5. Push the changes and create a PR targeting the `main` branch

## Workflow File Content

Create a file named `.github/workflows/python-ci-coverage.yml` with the following content:

```yaml
name: Python CI with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # Print flake8 version and installed plugins for debugging
        flake8 --version
        # Print the content of .flake8 file
        cat .flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=tests/
        # run full linting with all configured rules (informational only)
        flake8 . --count --statistics --exclude=tests/ || echo "Style issues found but continuing the build"

    - name: Type check with mypy
      run: |
        # Run mypy on all files except tests
        mypy fogis_reporter.py match_event_table_formatter.py match_context.py emoji_config.py

    - name: Test with pytest and coverage
      continue-on-error: true  # Allow tests to fail for now
      run: |
        # Run tests with coverage but don't fail the build if coverage is below threshold
        pytest --cov=. --cov-report=xml --cov-report=term || echo "Tests or coverage threshold failed but continuing the build"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        verbose: true

  pre-commit:
    runs-on: ubuntu-latest
    continue-on-error: true  # Allow pre-commit to fail for now
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit hooks
      run: |
        pre-commit run --all-files || echo "Pre-commit hooks failed but continuing the build"
```

## Additional Files Needed

In addition to the workflow file, you should also create a `.coveragerc` file in the root of the repository with the following content:

```ini
[run]
source = .
omit =
    # Omit test files
    tests/*
    # Omit virtual environment
    .venv/*
    venv/*
    # Omit setup files
    setup.py
    # Omit scripts directory
    scripts/*

[report]
# Exclude lines with pragma comments
exclude_lines =
    pragma: no cover
    def __repr__
    raise NotImplementedError
    if __name__ == .__main__.:    pass
    raise ImportError
    except ImportError:

# Show missing lines in report
show_missing = True

# Set a reasonable precision
precision = 2

[html]
directory = htmlcov

[xml]
output = coverage.xml

[json]
output = coverage.json
```

## README Updates

Also update the README.md to add a Codecov badge and documentation on test coverage:

1. Add this line after the title:

```markdown
[![codecov](https://codecov.io/gh/PitchConnect/fogis-reporter/branch/main/graph/badge.svg)](https://codecov.io/gh/PitchConnect/fogis-reporter)
```

2. Add this section after the "Pre-commit Hooks" section:

```markdown
#### Test Coverage with pytest-cov

We use pytest-cov to measure test coverage and ensure code quality:

```bash
# Run tests with coverage report
pytest --cov=. --cov-report=term

# Generate HTML coverage report
pytest --cov=. --cov-report=html
```

The configuration is in the `.coveragerc` file. We aim for a minimum coverage threshold of 60% and are continuously working to improve it.
```

## Notes

- The current test coverage is around 30%, so we'll need to continue improving it
- The CI/CD pipeline will continue even if tests fail or coverage is low
- We should aim to gradually increase the coverage threshold as we add more tests
